/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kinerjakaryawanahp.view;

/**
 *
 * @author TAKEN ZERO
 */
public class ViewMain extends javax.swing.JFrame {

    /**
     * Creates new form ViewMain
     */
    public ViewMain() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mnuLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuClose = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuDataKaryawan = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".:: Sistem AHP Kinerja Karyawan ::.");

        jMenu3.setText("Exit");

        mnuLogout.setText("Logout");
        jMenu3.add(mnuLogout);
        jMenu3.add(jSeparator1);

        mnuClose.setText("Close App");
        jMenu3.add(mnuClose);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Master Data");

        mnuDataKaryawan.setText("Data Karyawan");
<<<<<<< HEAD
        mnuDataKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDataKaryawanActionPerformed(evt);
            }
        });
=======
>>>>>>> 0122a3adffa9274585614b59f50c2fe74d486971
        jMenu4.add(mnuDataKaryawan);

        jMenuBar2.add(jMenu4);

        jMenu1.setText("Analisis");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Report");
        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void mnuDataKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDataKaryawanActionPerformed
        // TODO add your handling code here:
        new ViewKaryawan().setVisible(true);
    }//GEN-LAST:event_mnuDataKaryawanActionPerformed

=======
>>>>>>> 0122a3adffa9274585614b59f50c2fe74d486971
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnuClose;
    private javax.swing.JMenuItem mnuDataKaryawan;
    private javax.swing.JMenuItem mnuLogout;
    // End of variables declaration//GEN-END:variables
}
